services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "1905:8000"
    environment:
      - OPEN_IA_KEY=${OPEN_IA_KEY}
      - DB_URI=${DB_URI}
      - ENVIRONMENT=dev
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
