services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/app
    ports:
      - "1905:8000"
    environment:
      - OPEN_IA_KEY=${OPEN_IA_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - DB_URI=${DB_URI}
      - ENVIRONMENT=dev
      - DB_HOST= ${DB_HOST}
      - DB_PORT= ${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
